#!/bin/sh
# Hosts file adblock update.
# © 2013 Tom Vincent <http://tlvince.com/contact>

mvps="http://winhelp2002.mvps.org/hosts.txt"
tmp="$(mktemp /tmp/hosts.XXX)"

curl --output "$tmp" "$mvps"

head="# This MVPS HOSTS file is a free download from:            #"
tail="# \[end of entries generated by MVPS HOSTS\]"

# Quick sanity check
head -n 1 "$tmp" | grep -q "$head" || exit 1
tail -n 1 "$tmp" | grep -q "$tail" || exit 1

locals="/etc/hosts-local"
if [ -f "$locals" ]; then
  combined="$(mktemp /tmp/hosts.XXX)"
  cat "$tmp" "$locals" > "$combined"
  sudo mv "$combined" "/etc/hosts"
  rm "$combined"
else
  sudo mv "$tmp" "/etc/hosts"
  rm "$tmp"
fi
